kind: Service
apiVersion: v1
metadata:
  name: pod-service
spec:
  selector:
    project: expense
    env: de
  ports:
    - protocol: TCP
      port: 80
    



---

kind: Pod 
apiVersion: v1
metadata:
  name: pod
  labels:
    project: expense
    env: dev
spec:
  containers:
  - name: nginx 
    image: ngin