kind: Service
apiVersion: v1
metadata:
  name: svc-yaml
spec:
  selector:
    prject: expense
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---

kind: Pod
apiVersion: v1
metadata:
  name: podss
  labels:
    project: expense
    env: devss
spec:
  containers:
  - name: nginx
    image: nginx

