kind: Service
apiVersion: v1
metadata:
  name: pod-service
spec:
  selector:
    project: expense
    env: dev
  ports:
    - protocol: TCP
      port: 80
    - protocol: HTTP
      port: 80






---

kind: pod 
apiVersion: v1
metadata:
  name: pod
  labels:
    project: expense
    env: dev
spec:
  containers:
  - name: nginx 
    image: nginx