kind: Service
apiVersion: v1
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    project: expense
    component: dev
    version: 1.0.0 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    NodePort: 3007

---

kind: Pod
apiVersion: v1
metadata:
  name: nodeport-pod
  labels:
    project: expense
    component: dev
    version: 1.0.0 
spec:
  containers:
  - name: nginx
    image: nginx
