kind: Service
apiVersion: v1
metadata:
  name: node-port
spec:
  type: nodePort
  selector:
    project: expense
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 3007


---

kind: Pod
apiVersion: v1
metadata:
  name: pod-ebnv
  labels:
    project: expense
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx