kind: Service
apiVersion: v1
metadata:
  name: ld
spec:
  type: load-balancer
  selector: 
    app: env
    proect: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32676
  
