kind: Service
apiVersion: v1
metadata:
  name: ld
spec:
  type: LoadBalancer
  selector: 
    app: env
    proect: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32676
  
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-pod
  labels:
    app: env
    proect: expense
spec:
  containers:
  - name: nginx
    image: nginx
