kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginxx
  labels:
    app: frontend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
